typeidea/typeidea/urls.py
from django.conf.urls import url
from django.contrib import admin
# from ..blog.admin import custom_site  # mmp
from custom_site import custom_site
from blog.views import (
    IndexView, CategoryView, TagView,
    PostDetailView, SearchView, AuthorView
)
from config.views import LinkListView
from comment.views import CommentView
from django.contrib.sitemaps import views as sitemap_views
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
import xadmin
from .autocomplete import CategoryAutocompelete, TagAutocomplete
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from blog.apis import PostViewSet, CategoryViewSet
from rest_framework.routers import DefaultRouter

from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view



router = DefaultRouter()
router.register(r'post', PostViewSet, base_name='api-post')
router.register(r'category', CategoryViewSet, base_name='api-category')



urlpatterns = [
    url(r'^rss/$', LatestPostFeed(), name='rss'),
    url(r'^sitemap.xml$', sitemap_views.sitemap, {'sitemaps': {'posts': PostSitemap}}),

    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^author/(?P<owner_id>\d+)$', AuthorView.as_view(), name='author'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    url(r'^tag/(?P<tag_id>\d+)$', TagView.as_view(), name='tag-list'),
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),

    # url(r'^super_admin/', admin.site.urls, name='super-admin'),
    # url(r'^admin/', custom_site.urls, name='admin'),
    url(r'^admin/', xadmin.site.urls, ),

    url(r'^category-autocomplete/$', CategoryAutocompelete.as_view(), name='category-autocomplete'),
    url(r'^tag-autocomplete/$', TagAutocomplete.as_view(), name='tag-autocomplete'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


    url(r'^api/', include(router.urls,)),


    url(r'api/docs/', include_docs_urls(title='typeidea apis')),     # drf自带的接口文档
    url(r"^docs/$", get_swagger_view(title="tyepidea apis")),        # swagger接口文档

 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'__debug__/', include(debug_toolbar.urls)),
        # url(r'^silk/', include('silk.urls', namespace='silk')),
        ] + urlpatterns

typeidea/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import mistune
from django.utils.functional import cached_property

# from silk.profiling.profiler import silk_profile
# Create your models here.


class Category(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    name = models.CharField(max_length=50, verbose_name='名称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    is_nav = models.BooleanField(default=False, verbose_name='是否为导航')
    owner = models.ForeignKey(User, verbose_name='作者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '分类'

    @classmethod
    # @silk_profile(name='get_navs')
    def get_navs(cls):
        categories = cls.objects.filter(status=cls.STATUS_NORMAL)
        nav_categories = []
        normal_categories = []

        for cate in categories:
            if cate.is_nav:
                nav_categories.append(cate)
            else:
                normal_categories.append(cate)
        return {
            'navs': nav_categories,
            'categories':  normal_categories,
        }

    def __str__(self):
        return self.name


class Tag(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    name = models.CharField(max_length=10, verbose_name='名称')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    owner = models.ForeignKey(User, verbose_name='作者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '标签'

    def __str__(self):
        return self.name


class Post(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_DRAFT = 2
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
        (STATUS_DRAFT, '草稿')
    )
    title = models.CharField(max_length=255, verbose_name='标题')
    desc = models.CharField(max_length=1024, blank=True, verbose_name='摘要')
    content = models.TextField(verbose_name='正文', help_text='正文必须为MarkDown格式')
    content_html = models.TextField(verbose_name='正文 html 代码', blank=True, editable=False)
    is_md = models.BooleanField(default=False, verbose_name='正文格式切换为markdown',)
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    category = models.ForeignKey(Category, verbose_name='分类')
    tag = models.ManyToManyField(Tag, verbose_name='标签')
    owner = models.ForeignKey(User, verbose_name='作者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    pv = models.PositiveIntegerField(default=1)
    uv = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = verbose_name_plural = '文章'
        ordering = ['-id']

    @classmethod
    def hot_posts(cls):
        from django.core.cache import cache
        result = cache.get('hot_posts')
        if not result:
            result = cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-pv')
            cache.set('hot_posts', result, 10 * 60)
        return result
        # return cls.objects.filter(status=cls.STATUS_NORMAL).order_by('-pv')

    @staticmethod
    def get_by_tag(tag_id):
        try:
            tag = Tag.objects.get(id=tag_id)
        except Tag.DoesNotExist:
            tag = None
            post_lsit = []
        else:
            post_lsit = tag.post_set.filter(status=Post.STATUS_NORMAL).select_related('owner', 'category')

        return post_lsit, tag

    @staticmethod
    def get_by_category(categoty_id):
        try:
            category = Category.objects.get(id=categoty_id)
        except Category.DoesNotExist:
            category = None
            post_list = []
        else:
            post_list = category.post_set.filter(status=Post.STATUS_NORMAL).select_related('owner', 'category')

        return post_list, category

    @classmethod
    def latest_posts(cls, with_related=True):
        queryset = cls.objects.filter(status=cls.STATUS_NORMAL)
        if with_related:
            queryset = queryset.select_related('owner', 'category').prefetch_related('tag')
        return queryset

    def save(self, *args, **kwargs):
        if self.is_md:
            self.content_html = mistune.markdown(self.content)
        else:
            self.content_html = self.content
        super().save(*args, **kwargs)

    @cached_property
    def tags(self):
        return ','.join(self.tag.values_list('name', flat=True))

    def __str__(self):
        return self.title

typeidea/config/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.loader import render_to_string

# Create your models here.


class Link(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    title = models.CharField(max_length=10, verbose_name='标题')
    href = models.URLField(verbose_name='链接')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    weight = models.PositiveIntegerField(default=1, choices=zip(range(1, 6), range(1, 6)), verbose_name='权重',
                                         help_text='权重高展示位置靠前')
    owner = models.ForeignKey(User, verbose_name='作者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '友链'


class SideBar(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '展示'),
        (STATUS_DELETE, '隐藏'),
    )

    DISPLAY_HTML = 1
    DISPLAY_LATEST = 2
    DISPLAY_HOT = 3
    DISPLAY_COMMENT = 4
    SIDE_TYPE = (
        (DISPLAY_HTML, 'HTML'),
        (DISPLAY_LATEST, '最新文章'),
        (DISPLAY_HOT, '最热文章'),
        (DISPLAY_COMMENT, '最近评论'),
    )
    title = models.CharField(max_length=255, verbose_name='标题')
    display_type = models.PositiveIntegerField(default=DISPLAY_HTML, choices=SIDE_TYPE, verbose_name='展示类型')
    content = models.CharField(max_length=500, blank=True, verbose_name='内容', help_text='如果设置的不是HTML类型，可为空')
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name='状态')
    owner = models.ForeignKey(User, verbose_name='作者')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    class Meta:
        verbose_name = verbose_name_plural = '侧边栏'

    @classmethod
    def get_all(cls):
        return cls.objects.filter(status=cls.STATUS_NORMAL)

    @property
    def content_html(self):
        '''直接渲染模板'''
        from blog.models import Post
        from comment.models import Comment

        result = ''
        if self.display_type == self.DISPLAY_HTML:
            result = self.content
        elif self.display_type == self.DISPLAY_LATEST:
            context = {
                'posts': Post.latest_posts(with_related=False)
            }
            result = render_to_string('config/blocks/sidebar_posts.html', context)
        elif self.display_type == self.DISPLAY_HOT:
            context = {
                'posts': Post.hot_posts()
            }
            result = render_to_string('config/blocks/sidebar_posts.html', context)
        elif self.display_type == self.DISPLAY_COMMENT:
            context ={
                'comments': Comment.objects.filter(status=Comment.STATUS_NORMAL)
            }
            result = render_to_string('config/blocks/sidebar_comments.html', context)

        return result

    def __str__(self):
        return self.title

typeidea/blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from config.models import SideBar
from django.views.generic import DetailView, ListView
from django.shortcuts import get_object_or_404
from django.db.models import Q, F
from comment.models import Comment
from comment.forms import CommentForm
from datetime import date
from django.core.cache import cache

# Create your views here.


# def post_list(request, category_id=None, tag_id=None):
#     tag = None
#     category = None
#     if tag_id:
#         posts_list, tag = models.Post.get_by_tag(tag_id)
#     elif category_id:
#         posts_list, category = models.Post.get_by_category(category_id)
#     else:
#         posts_list = models.Post.latest_posts()
#
#     context = {
#         'category': category,
#         'tag': tag,
#         'post_list': posts_list,
#         'sidebars': SideBar.get_all()
#     }
#     context.update(models.Category.get_navs())
#     return render(request, 'blog/list1.html', context=context)


# def post_detail(request, post_id=None):
#     try:
#         post = models.Post.objects.get(id=post_id)
#     except models.Post.DoesNotExist:
#         post = None
#     content = {
#         'post': post,
#         'sidebars': SideBar.get_all()
#     }
#     return render(request, 'blog/detail.html', context=content)


# class PostDetailView(DetailView):
#     model = models.Post
#     template_name = 'blog/detail.html'
#     # context_object_name = 'aaa'


# class PostListView(ListView):
#     queryset = models.Post.latest_posts()
#     paginate_by = 1  # 每页一条数据
#     context_object_name = 'post_list'  # 默认是object_list
#     template_name = 'blog/list1.html'


class CommonViewMinxin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                'sidebars': SideBar.get_all(),
            }
        )
        context.update(models.Category.get_navs())
        return context


class IndexView(CommonViewMinxin, ListView):
    queryset = models.Post.latest_posts()
    paginate_by = 2
    context_object_name = 'post_list'
    template_name = 'blog/list1.html'


class SearchView(IndexView):
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context.update({
    #         'keyword': self.request.GET.get('keyword', '')
    #     })
    #     return context

    def get_queryset(self):
        queryset = super().get_queryset()
        keyword = self.request.GET.get('keyword', '')
        if not keyword:
            return queryset
        return queryset.filter(Q(title__icontains=keyword) | Q(desc__icontains=keyword))


class AuthorView(IndexView):
    def get_queryset(self):
        queryset = super().get_queryset()
        author_id = self.kwargs.get('owner_id')
        return queryset.filter(owner_id=author_id)


class CategoryView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs.get('category_id')
        category = get_object_or_404(models.Category, pk=category_id)
        context.update({
            'category': category
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id)


class TagView(IndexView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_id = self.kwargs.get('tag_id')
        tag = get_object_or_404(models.Tag, pk=tag_id)
        context.update({
            'tag': tag,
        })
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        tag_id = self.kwargs.get('tag_id')
        return queryset.filter(tag_id=tag_id)


class PostDetailView(CommonViewMinxin, DetailView):
    queryset = models.Post.latest_posts()
    # model = models.Post
    template_name = 'blog/detail.html'

    context_object_name = 'post'
    pk_url_kwarg = 'post_id'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.handle_visited()
        return response

        # models.Post.objects.filter(pk=self.object.id).update(pv=F('pv')+1, uv=F('uv')+1)
        #
        # #  查看orm对应的sql语句
        # from django.db import connection
        # print(connection.queries)
        # return response

    def handle_visited(self):
        increase_pv = False
        increase_uv = False
        uid = self.request.uid
        pv_key = 'pv:%s:%s' % (uid, self.request.path)
        uv_key = 'uv:%s:%s' % (uid, self.request.path)
        if not cache.get(pv_key):
            increase_pv = True
            cache.set(pv_key, 1, 1*60)
        if not cache.get(uv_key):
            increase_uv = True
            cache.set(uv_key, 1, 24*60*60)
        if increase_pv and increase_uv:
            models.Post.objects.filter(pk=self.object.id).update(pv=F('pv')+1,
                                                                 uv=F('uv')+1)
        elif increase_pv:
            models.Post.objects.filter(pk=self.object.id).update(pv=F('pv')+1)
        elif increase_uv:
            models.Post.objects.filter(pk=self.object.id).update(uv=F('uv') + 1)

typeidea/typeidea/themes/bootstrap/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}首页{% endblock %} - typeidea 博客系统</title>
    <style>
        .post {
            margin-bottom: 5px;
        }
    </style>

    {% block extra_head %}
    {% endblock %}

</head>
<body>
    <div class="container head">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a  class="navbar-brand" href="#">首页</a>
            <a  class="navbar-brand" href="#">置顶分类</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                   {% for cate in navs %}
                       <li class="nav-item">
                           <a class="nav-link" href="{% url 'category-list' cate.id %}">{{ cate.name }}</a>
                       </li>
                    {% endfor %}

                </ul>
                <form class="form-inline my-2 my-lg-0" action='/search/' method="GET">
                    <input class="form-control mr-sm-2" style="search" placeholder="请输入title或者desc"
                        aria-label="Search" type="search" name="keyword" >
                    <button class="btn btn-outline-success" type="submit">搜索</button>
                </form>
            </div>
        </nav>
        <div class="jumbotron">
            <h1 class="display-4">Typeidea</h1>
            <p class="lead">基于Django的多人博客系统</p>
        </div>
    </div>
    <div class="container main">
        <div class="row">
            <div class="col-9  post-list">
                {% block main %}
                {% endblock %}
            </div>
            <div class="col-3">
            {% load cache %}
            {% cache  50 sidebar %}
                {% block sidebar %}
                    {% for sidebar in sidebars %}
                        <div class="card sidebar">
                            <div class="card-body">
                                <h3 style="color:#ff5871">{{ sidebar.get_display_type_display }}</h3>
                                <h4 class="card-title">{{ sidebar.title }}</h4>
                                <p>{{ sidebar.content_html }}</p>
                            </div>
                        </div>
                    {% endfor %}
                {% endblock %}
             {% endcache %}
            </div>
        </div>
    </div>

    <hr>
    <div class="rss">
        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
    </div>
    <hr>
    <footer class="footer">
        {% block footer %}
            <div class="container">
            <hr>
            <nav class="nav category">
                <a  class="navbar-brand" href="#" style="color: #ff5871">其他分类</a>
                {% for cate in categories %}
                     <a href="{% url 'category-list' cate.id %}" class="nav-link">{{ cate.name }}</a>
                {% endfor %}

            </nav>
        </div>
        <div class="container power">
            <span class="text-muted">Power by Typeidea@the5fire</span>
        </div>
        {% endblock %}
    </footer>
</body>
</html>

typeidea/typeidea/themes/bootstrap/templates/blog/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django 企业开发实战</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container" style="border: 1px solid red;">
        <h1>hello, world</h1>
    </div>
    <div class="container" style="border: 1px solid red">
        <div class="row">
            <div class="col-9" style="border: 1px solid blue">
                <div style="height: 500px">内容区</div>
            </div>
            <div class="col-3" style="border: 1px solid blue;">
                <div style="height: 500px">边框区</div>
            </div>
        </div>
    </div>
    <footer class="container" style="border: 1px solid red;">
        底部footer区域
    </footer>
</body>
</html>

typeidea/typeidea/themes/bootstrap/templates/blog/detail.html
{% extends './base.html' %}
{% load comment_block %}
{% block title %}
    {{ post.title }}
{% endblock %}

{% block extra_head %}

    <link rel="stylesheet" href="https://cdn.bootcss.com/highlight.js/9.12.0/styles/googlecode.min.css">
    <script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block main %}
    {% if post %}
        <div class="card post">
            <div class="card-body">
                 <h1>{{ psot.title }}</h1>
                 <span>分类：{{ post.category.name }}</span>
                 <span>作者：{{ post.owner.username }}</span>
                <hr>
                <p class="card-text">内容: {% autoescape off %}{{ post.content_html }}{% endautoescape %}</p>
            </div>
        </div>
    {% endif %}
    <hr>
    {% comment_block request.path %}
{% endblock %}

typeidea/typeidea/themes/bootstrap/templates/blog/list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>Document</title>
    <style>
        .post {
            margin-bottom: 5px;
        }
    </style>
</head>
<body>
    <div class="container head">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a  class="navbar-brand" href="#">首页</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Python</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Django 实战</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="#">Tornado</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" style="search" palaceholder="Search"
                        aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">搜索</button>
                </form>
            </div>
        </nav>
        <div class="jumbotron">
            <h1 class="display-4">Typeidea</h1>
            <p class="lead">基于Django的多人博客系统</p>
        </div>
    </div>
    <div class="container main">
        <div class="row">
            <div class="rol-9  post-list">
                <div class="card post">
                    <div class="card-body">
                        <h5 class="card-title"><a href="#">这里是标题</a></h5>
                        <span class="card-link">作者：<a href="#">胡阳</a></span>
                        <span class="card-link">分类：<a href="#">Python</a></span>
                        <span class="card-link">标签：
                            <a href="#">Python</a>
                            <a href="#">Django</a>
                            <a href="#">经验</a>

                        </span>

                        <p class="card-text">Some quick example text to build on the
                            card title and make up the bulk  of the card's content.
                            <a href="#">完整内容</a>
                        </p>
                    </div>
                </div>
            <div class="card post">
                <div class="card-body">
                    <h5 class="card-title"><a href="#">这里是标题</a></h5>
                    <span class="card-link">作者：<a href="#">胡阳</a></span>
                    <span class="card-link">分类：<a href="#">Python</a></span>
                    <span class="card-link">标签：
                        <a href="#">Python</a>
                        <a href="#">Django</a>
                        <a href="#">经验</a>
                    </span>
                     <p class="card-text">Some quick example text to build on the
                            card title and make up the bulk  of the card's content.
                            <a href="#">完整内容</a>
                        </p>
                </div>
            </div>
            <div class="card post">
                <div class="card-body">
                    <h5 class="card-title"><a href="#">这里是标题</a></h5>
                    <span class="card-link">作者：<a href="#">the5fire</a></span>
                    <span class="card-link">分类：<a href="#">Python</a></span>
                    <span class="card-link">标签：
                        <a href="#">Python</a>
                        <a href="#">Django</a>
                        <a href="#">经验</a>
                    </span>
                     <p class="card-text">Some quick example text to build on the
                            card title and make up the bulk  of the card's content.
                            <a href="#">完整内容</a>
                        </p>
                </div>
            </div>
            <a href="?page={{ page_obj.previous_page_number }}">'上一页'</a>
            Page  1 of 1.
            <a href="?page={{ page_obj.next_page_number }}">'下一页'</a>
        </div>
            <div class="col-3">
            <div class="card sidebar">
                <div calss="card-body">
                    <h4 class="card-title">关于博主</h4>
                    <p>
                        网名： the5fire , 多年Python开发gcs
                    </p>
                </div>
            </div>
        </div>
        </div>

    <footer class="footer">
        <div class="container">
            <hr>
            <nav class="nav category">
                <a href="#" class="nav-link">读书</a>
                <a href="#" class="nav-link">产品</a>
                <a href="#" class="nav-link">工作经历</a>
            </nav>
        </div>
        <div class="container power">
            <span class="text-muted">Power by Typeidea@the5fire</span>
        </div>
    </footer>
</body>
</html>

typeidea/typeidea/themes/bootstrap/templates/blog/list1.html
{% extends './base.html' %}
{% block title %}
    {% if tag %}
    标签页：{{ tag.name }}

    {% elif category %}
    分类页：{{ category.name }}
    {% else %}
        -首页-
    {% endif %}
{% endblock %}


{% block main %}
         {% for post in post_list %}
             <div class="card post">
                <div class="card-body">
                    <h5  class="card-link"><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h5>
                    <sapn class="card-link">作者：<a href="#">{{ post.owner.username }}</a> </sapn>
                    <sapn class="card-link">分类：<a href="{% url 'category-list' post.category.id %}">{{ post.owner.username }}</a></sapn>
                    <sapn class="card-link">标签：
                        {% for tag in post.tag.all %}
                        <a href="{% url 'tag-list' tag.id %}">{{ tag.name }}</a>
                        {% endfor %}
                    </sapn>
                    <sapn class="card-link">作者：<a href="{% url 'author' post.owner.id %} ">查看{{ post.owner.username }}的文章</a> </sapn>
                <p class="card-text">{{ psot.desc }}<a href="{% url  'post-detail' post.id %}">完整内容</a></p>
                </div>
             </div>
         {% endfor %}

     {% if page_obj %}
         {% if page_obj.has_previous %}
             <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
             {% endif %}
             Page {{ page_obj.number }} of  {{ paginator.num_pages }}
         {% if page_obj.has_next %}
             <a href="?page={{ page_obj.next_page_number }}">下一页</a>
             {% endif %}
     {% endif %}

{% endblock %}